---
title: "Floral development and pollination of _Centropogon granulosus_ in an Andean cloud forest"
author:
date: ""
output: 
  word_document:
    fig_caption: yes
    reference_docx: centropogon_biology_reference.docx
  # html_document:
  #   number_sections: no
  #   theme: flatly
   # pdf_document:
   #  latex_engine: xelatex
bibliography: centropogon_biology.bib
csl: cell.csl
link-citations: true #'yes' for html, 'true' for pdfs
linkcolor: blue
urlcolor: blue
citecolor: blue


---

**Author Names**: <br> 
Mannfred M.A. Boehm$^{1,2,*}$, David Guevara Apaza$^{3}$ + others

$^*$**Corresponding Author**: mannfred.boehm@ubc.ca

**Author affiliations**: <br> 
$^1$Department of Botany, University of British Columbia,
3156 - 6270 University Boulevard, Vancouver, BC, Canada, V6T 1Z4. <br>

$^2$Biodiversity Research Centre, University of British Columbia, 2212 Main Mall, Vancouver, BC, Canada, V6T 1Z4. <br>

$3$Facultad de Ciencias Biológicas, Universidad San Antonio Abad del Cusco, Av. de La Cultura 773, Cusco 08000, Peru. 

**Submission Type**: Brief Communications 

**Abstract**: (200 max for Botany) 

**Main Body**: (4200 max for Botany) 

**Figures**: # Figures

**Keywords**: (3-6 for Botany)



\newpage


#### Acknowledgements

Put Acknowledgements here. 


\newpage

#### Introduction 


The Andes comprise the highest mountains in the western hemisphere and are one of the most biodiverse regions on Earth [@myers_2000]. With a mean elevation of 4000 m, the Andes encompass a wide environmental gradient ranging from warm Amazonian rainforests, to dry, montane grasslands. Following Andean orogeny, flowering plants dispersed and adapted to these myriad niches, e.g. _Lupinus_ L. [Fabaceae, @hughes_2006], eucentropogonids [Campanulaceae, @lagomarsino_2016], epiphytic orchids [Epidendroideae, @perez_2017]. Today, about 10% of global angiosperm diversity is found in the Andes eco-region [@joppa_2011]. 

&emsp;&emsp; Plant-pollinator coevolution offers a powerful model explaining the rapid diversification of the Andean flora [e.g. @kay_2005;@lagomarsino_2017; @serrano_2017;]. As a plant species expands into a novel montane environment floral traits may drift, evolve via pleiotropy, or adapt to a pre-existing pollinator community [@harder_2009; @smith_2016]. Subsequently, divergence in floral phenotype can be reinforced when reciprocal adaptation between the plant and pollinator promotes floral isolation [sensu @grant_1949]. However, despite compelling phenotypic and phylogenetic evidence, many putative cases of pollinator-driven plant diversification lack a direct observation of floral visitation and pollination. In this study, we aimed to test the theory of hummingbird-mediated diversification in _Centropogon_ C.Presl (Campanulaceae) by recording pollinator visits, performing a pollinator exclusion experiment, and synthesizing evidence from related studies. 

Start paragraph about Centropogon. 





X The Andes have a lot of plants
X It's good to know this because the evolution of pollination syndromes is in many clades, closely linked to speciation. 
- Recently, Centropogon has been of interest because it is young and speciose
- Summarise what we know about Centropogon evolution/speciation 
  - Figure 1. Elevational distribution.
- In this paper we detail the development and pollination of Centropogon granulosus inhabiting a cloud forest in southeastern Peru. 

\newpage

#### Methods

- Dates in the field. 
- Pollination exclusion experiment [see Figure 1 in @sun_2017]. How many Centropogon sampled (n=???)
- camera traps (number of traps, number of Centropogon)
- Using camera trap data to manually record Sicklebills

\newpage

#### Results: 
  - Figure 2. Developmental stages of Centropogon. 
  - Figure 3. Pollination by Sicklebills
  - Discuss things that live in or around the flowers (ants (cite Stein and LauraLago), mites (cite MacGregor), arachnids)
  
# References
  

